"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "bn";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.treatment": "Treatment",
    "nav.contact": "Contact",
    "nav.getHelp": "Get Help",

    // Hero Section
    "hero.tagline": "The best mental health solution",
    "hero.title": "Brain And Life Hospital",
    "hero.description": "We provide compassionate, evidence-based mental health care in a safe, supportive environment—helping individuals restore balance, build resilience, and rediscover hope.",
    "hero.learnMore": "Learn More",
    "hero.contactUs": "Contact Us",
    "hero.followUs": "Follow us:",

    // MD Message
    "md.badge": "A message from leadership",
    "md.title": "Hear What Our Managing Director Has to Say",
    "md.quote": "At our hospital, we believe mental health care begins with compassion. Every individual who walks through our doors is treated with dignity, understanding, and respect. Our commitment is not just to heal minds, but to restore hope, purpose, and quality of life.",
    "md.author": "— Md Fokrul Hossain, Managing Director, Brain And Life Hospital",
    "md.readMore": "Read More",

    // MD Page
    "mdPage.heroBadge": "Message from Managing Director",
    "mdPage.heroTitle": "Compassionate Care for Mental Wellness",
    "mdPage.heroDescription": "At Brain and Life Hospital, we understand that mental health challenges affect not just individuals, but entire families. Our mission is to provide comprehensive, compassionate care that supports recovery and healing.",
    "mdPage.section1Title": "Understanding Mental Health Challenges",
    "mdPage.section1Para1": "The pressures of work, family problems, relationship matters, and memories of the past can become overwhelming—especially when you have children to care for. When these challenges become too much to bear, they can lead to mental health issues that require professional support and treatment.",
    "mdPage.section1Para2": "Substance use disorders are a serious concern in our society. When addiction enters a family, it affects everyone—not just the individual struggling with addiction. Families often find themselves in turmoil, facing difficult decisions about how to help their loved ones.",
    "mdPage.section2Title": "Our Treatment Approach",
    "mdPage.section2Para1": "At Brain and Life Hospital, we recognize that each patient requires individualized care. Our treatment plans vary according to different modes of counseling and care needs. We understand that addiction is a disease that requires medical intervention, psychological support, and family involvement.",
    "mdPage.section2Para2": "Unfortunately, many families reach a point where they feel treatment is no longer necessary or effective. Some may give up hope due to repeated relapses. Family members sometimes distance themselves from the person struggling with addiction, which can lead to feelings of neglect and isolation—further complicating the recovery process.",
    "mdPage.section3Title": "Comprehensive Inpatient Care",
    "mdPage.section3Para1": "For patients requiring intensive treatment, our hospital provides a safe, supportive environment. Typically, patients stay with us for 15-30 days, during which time they receive comprehensive care including medical treatment, therapy, and family counseling.",
    "mdPage.section3Para2": "We believe that recovery involves the whole family. Our approach emphasizes rebuilding family connections and ensuring that both the patient and their family members receive the support they need. Regular medication management and ongoing therapy are essential components of treatment, as they help prevent relapse and support long-term recovery.",
    "mdPage.section4Title": "Long-term Recovery Support",
    "mdPage.section4Para1": "Recovery is an ongoing journey that extends beyond the hospital stay. After discharge, patients need continued support to maintain their progress. This includes staying away from old friends and environments that may trigger relapse, and building new, healthy relationships and routines.",
    "mdPage.section4Para2": "At Brain and Life Hospital, we are committed to providing the support and care needed for lasting recovery. Our team works tirelessly to help patients and their families navigate the path to healing and wellness.",
    "mdPage.ctaTitle": "Need Support?",
    "mdPage.ctaDescription": "If you or a loved one needs help, our compassionate team is here to guide you.",
    "mdPage.contactUs": "Contact Us",
    "mdPage.viewServices": "View Services",

    // Specialists
    "specialists.badge": "Our Expert Team",
    "specialists.title": "Meet Our Specialist Psychiatrists",
    "specialists.description": "Nationally recognized consultants in psychiatry and psychotherapy, dedicated to compassionate, evidence-based mental health care.",
    "specialists.readMore": "Read More",
    "specialists.mohit.name": "Prof. Dr. Mohit",
    "specialists.mohit.lastName": "Kamal",
    "specialists.mohit.description": "Prof. Dr. M A Mohit Kamal is a distinguished psychiatrist and psychotherapist with extensive experience in mental health care. As a Senior Chief Consultant at LABAID Cardiac Hospital, he provides comprehensive psychiatric care and psychotherapy services.",
    "specialists.rabbani.name": "Prof. Dr. Golam",
    "specialists.rabbani.lastName": "Rabbani",
    "specialists.rabbani.description": "Prof. Dr. Golam Rabbani is a distinguished psychiatrist and mental health specialist with extensive experience in psychiatric care and psychotherapy. As Chief Consultant at Brain and Life Hospital, he provides comprehensive mental health services with a patient-centered approach and evidence-based treatments.",
    "specialists.mandal.name": "Prof. Dr. Mahadeb Chandra",
    "specialists.mandal.lastName": "Mandal",
    "specialists.mandal.description": "Prof. Dr. Mahadeb Chandra Mandal is a renowned psychiatrist and mental health expert with extensive experience in clinical psychiatry and psychotherapy. As Senior Consultant at Brain and Life Hospital, he specializes in comprehensive mental health care with a focus on evidence-based treatments and patient recovery.",

    // Specialist Detail Pages - Common
    "specialistDetail.chiefConsultant": "Chief Consultant",
    "specialistDetail.seniorChiefConsultant": "Senior Chief Consultant",
    "specialistDetail.seniorConsultant": "Senior Consultant",
    "specialistDetail.qualifications": "Qualifications",
    "specialistDetail.currentPosition": "Current Position",
    "specialistDetail.about": "About",
    "specialistDetail.experience": "Experience",
    "specialistDetail.professionalExperience": "Professional Experience",
    "specialistDetail.currentRoles": "Current Roles",
    "specialistDetail.previousPositions": "Previous Positions",
    "specialistDetail.expertise": "Expertise",
    "specialistDetail.areasOfExpertise": "Areas of Expertise",

    // Rabbani Detail Page
    "specialistDetail.rabbani.title": "Chief Consultant (Psychiatry & Mental Health)",
    "specialistDetail.rabbani.qualifications": "MBBS: Rajshahi Medical College, University of Rajshahi, Bangladesh\nFCPS: Bangladesh College of Physicians and Surgeons",
    "specialistDetail.rabbani.currentPosition": "Professor of Psychiatry\nChief Consultant (Psychiatry & Mental Health)\nBrain and Life Hospital",
    "specialistDetail.rabbani.aboutTitle": "About Dr. Golam Rabbani",
    "specialistDetail.rabbani.about1": "Prof. Dr. Golam Rabbani is a distinguished psychiatrist and mental health specialist with extensive experience in psychiatric care and psychotherapy. As Chief Consultant at Brain and Life Hospital, he provides comprehensive mental health services with a patient-centered approach and evidence-based treatments.",
    "specialistDetail.rabbani.about2": "With advanced qualifications including MBBS from Rajshahi Medical College and FCPS from Bangladesh College of Physicians and Surgeons, Dr. Rabbani brings decades of experience in diagnosing and treating various mental health conditions. His expertise combines pharmacological treatments with psychotherapy, ensuring holistic care for patients.",
    "specialistDetail.rabbani.currentRole1": "Professor of Psychiatry at Brain and Life Hospital",
    "specialistDetail.rabbani.currentRole2": "Chief Consultant (Psychiatry & Mental Health)",
    "specialistDetail.rabbani.currentRole3": "Head of Mental Health Research Department",
    "specialistDetail.rabbani.previousRole1": "Senior Consultant Psychiatrist at Dhaka Medical College Hospital",
    "specialistDetail.rabbani.previousRole2": "Associate Professor of Psychiatry at University of Dhaka",
    "specialistDetail.rabbani.previousRole3": "Clinical Director, Mental Health Institute Bangladesh",
    "specialistDetail.rabbani.previousRole4": "Research Fellow at WHO Mental Health Program",
    "specialistDetail.rabbani.expertise1": "Clinical Psychiatry",
    "specialistDetail.rabbani.expertise1Desc": "Comprehensive psychiatric diagnosis and treatment",
    "specialistDetail.rabbani.expertise2": "Psychotherapy",
    "specialistDetail.rabbani.expertise2Desc": "Cognitive behavioral therapy and counseling",
    "specialistDetail.rabbani.expertise3": "Mental Health Research",
    "specialistDetail.rabbani.expertise3Desc": "Clinical research and evidence-based practice",

    // Mohit Detail Page
    "specialistDetail.mohit.title": "Senior Chief Consultant (Psychiatry & Psychotherapy)",
    "specialistDetail.mohit.qualifications": "MBBS\nM.Phil. (Psychiatry)\nFCPS (Psychiatry)",
    "specialistDetail.mohit.currentPosition": "Professor of Psychotherapy\nSenior Chief Consultant (Psychiatry & Psychotherapy)\nLABAID Cardiac Hospital",
    "specialistDetail.mohit.aboutTitle": "About Dr. M A Mohit Kamal",
    "specialistDetail.mohit.about1": "Prof. Dr. M A Mohit Kamal is a distinguished psychiatrist and psychotherapist with extensive experience in mental health care. As a Senior Chief Consultant at LABAID Cardiac Hospital, he provides comprehensive psychiatric care and psychotherapy services.",
    "specialistDetail.mohit.about2": "With his advanced qualifications including MBBS, M.Phil. in Psychiatry, and FCPS in Psychiatry, Dr. Kamal brings a wealth of knowledge and expertise to his practice. His commitment to mental health extends beyond clinical practice to academic leadership and institutional development.",
    "specialistDetail.mohit.currentRole1": "Professor of Psychotherapy",
    "specialistDetail.mohit.currentRole2": "Senior Chief Consultant (Psychiatry & Psychotherapy) at LABAID Cardiac Hospital",
    "specialistDetail.mohit.previousRole1": "Former Head of Psychotherapy",
    "specialistDetail.mohit.previousRole2": "Former Academic Course Director MD (Psychiatry)",
    "specialistDetail.mohit.previousRole3": "Former Director, National Institute of Mental Health, Dhaka",
    "specialistDetail.mohit.expertise1": "Psychiatry",
    "specialistDetail.mohit.expertise1Desc": "Comprehensive psychiatric diagnosis and treatment",
    "specialistDetail.mohit.expertise2": "Psychotherapy",
    "specialistDetail.mohit.expertise2Desc": "Evidence-based therapeutic interventions",
    "specialistDetail.mohit.expertise3": "Academic Leadership",
    "specialistDetail.mohit.expertise3Desc": "Medical education and training",

    // Mandal Detail Page
    "specialistDetail.mandal.title": "Senior Consultant (Psychiatry & Mental Health)",
    "specialistDetail.mandal.qualifications": "MBBS\nMD (Psychiatry)\nFCPS (Psychiatry)",
    "specialistDetail.mandal.currentPosition": "Professor of Psychiatry\nSenior Consultant (Psychiatry & Mental Health)\nBrain and Life Hospital",
    "specialistDetail.mandal.aboutTitle": "About Dr. Mahadeb Chandra Mandal",
    "specialistDetail.mandal.about1": "Prof. Dr. Mahadeb Chandra Mandal is a renowned psychiatrist and mental health expert with extensive experience in clinical psychiatry and psychotherapy. As Senior Consultant at Brain and Life Hospital, he specializes in comprehensive mental health care with a focus on evidence-based treatments and patient recovery.",
    "specialistDetail.mandal.about2": "With advanced qualifications including MBBS, MD in Psychiatry, and FCPS in Psychiatry, Dr. Mandal brings years of clinical experience in diagnosing and treating complex mental health conditions. His approach integrates modern psychiatric practices with compassionate care, ensuring optimal outcomes for patients with various mental health challenges.",
    "specialistDetail.mandal.currentRole1": "Professor of Psychiatry at Brain and Life Hospital",
    "specialistDetail.mandal.currentRole2": "Senior Consultant (Psychiatry & Mental Health)",
    "specialistDetail.mandal.currentRole3": "Clinical Supervisor for Psychiatry Residents",
    "specialistDetail.mandal.previousRole1": "Consultant Psychiatrist at National Institute of Mental Health",
    "specialistDetail.mandal.previousRole2": "Associate Professor of Psychiatry at Bangabandhu Sheikh Mujib Medical University",
    "specialistDetail.mandal.previousRole3": "Senior Psychiatrist at Dhaka Medical College Hospital",
    "specialistDetail.mandal.previousRole4": "Medical Officer at Mental Health Department, Ministry of Health",
    "specialistDetail.mandal.expertise1": "Adult Psychiatry",
    "specialistDetail.mandal.expertise1Desc": "Treatment of mood disorders and anxiety conditions",
    "specialistDetail.mandal.expertise2": "Cognitive Therapy",
    "specialistDetail.mandal.expertise2Desc": "Cognitive behavioral therapy and mindfulness-based interventions",
    "specialistDetail.mandal.expertise3": "Medical Education",
    "specialistDetail.mandal.expertise3Desc": "Training and supervision of psychiatry residents",

    // Steps
    "steps.badge": "Fastest solution",
    "steps.title": "4 Easy Steps And Get Your Solution",
    "steps.step1.title": "Share what you're going through",
    "steps.step1.desc": "Call us or send a message with a few details about your mood, thoughts, or behaviour so our team can understand how to best support you.",
    "steps.step2.title": "Meet with a specialist",
    "steps.step2.desc": "You'll have a confidential consultation with one of our psychiatrists or psychologists to discuss your history, concerns, and goals.",
    "steps.step3.title": "Get your treatment plan",
    "steps.step3.desc": "Together we create a personalized plan that can include therapy, medication, rehabilitation, or a combination of approaches that fit your life.",
    "steps.step4.title": "Start care with ongoing support",
    "steps.step4.desc": "Begin your treatment with regular follow‑ups, family guidance, and 24/7 support so you never feel alone in your recovery journey.",

    // Doctors
    "doctors.badge": "Our medical team",
    "doctors.title": "Meet Our Compassionate Doctors",
    "doctors.description": "Our skilled medical professionals provide 24/7 care, combining medical expertise with empathy to support patients through every step of their mental health journey.",

    // Staff
    "staff.badge": "Our Team",
    "staff.title": "Why Choose Brain & Life",
    "staff.description": "Experience excellence in mental health care with our modern approach and dedicated professionals.",

    // CTA
    "cta.title": "Ready to Take the First Step?",
    "cta.description": "Our compassionate team is here to help you or your loved one begin the journey toward recovery and wellness.",
    "cta.contact": "Contact Us Today",
    "cta.call": "Call 24/7 Helpline",

    // Footer
    "footer.tagline": "We pickup patient from home and no attendance required.",
    "footer.description": "Providing compassionate, evidence-based mental health care in a safe and supportive environment.",
    "footer.navigation": "Navigation",
    "footer.contact": "Contact",
    "footer.followUs": "Follow Us",
    "footer.socialDesc": "Stay connected with us on social media",
    "footer.copyright": "All Rights Reserved.",
    "footer.madeWith": "Made with",
    "footer.for": "for mental wellness",

    // Hero banner text
    "hero.banner": "Compassionate, evidence-based care",
    "hero.bannerSub": "Your journey to wellness starts here.",

    // Services Page
    "services.badge": "Our Services",
    "services.title": "Compassionate Mental Health &",
    "services.titleHighlight": "Addiction Care",
    "services.description": "At Brain and Life Hospital, we combine evidence-based treatment with a calming, therapeutic environment. Our multi-disciplinary team supports you 24/7—through crisis, recovery, and long-term wellness.",
    "services.bookConsultation": "Book a Confidential Consultation",
    "services.emergencySupport": "24/7 Emergency Support",
    "services.emergencySupportDesc": "Always-on care for mental health and addiction crises.",
    "services.emergencyCare": "Emergency Care",
    "services.holisticSupport": "Holistic Support",
    "services.safeEnvironment": "Calm Environment",
    "services.programs": "Programs",
    "services.specializedServices": "Specialized Services",
    "services.specializedDesc": "Comprehensive treatment programs tailored to each individual's needs—delivered with compassion, safety, and expertise.",
    "services.expertise": "Expertise",
    "services.conditionsWeTreat": "Conditions We",
    "services.conditionsHighlight": "Specialize In",
    "services.conditionsDesc": "Compassionate care for a wide range of mental health conditions and substance use disorders.",
    "services.team": "Team",
    "services.expertTeam": "Expert Team",
    "services.confidentialCare": "Confidential, judgment-free care",
    "services.confidentialDesc": "Every journey is treated with dignity and respect.",
    "services.emergencyServices": "24/7 Emergency & Support Services",
    "services.emergencyDesc": "Mental health crises don't wait for business hours. Our dedicated team is available around the clock to provide immediate care, support, and intervention when you need it most.",
    "services.crisisHotline": "Crisis Hotline",
    "services.immediate": "Immediate",
    "services.immediateResponse": "Emergency Response",
    "services.expert": "Expert",
    "services.safe": "Safe",
    "services.our": "Our",
    "services.team1": "Nationally & Internationally Renowned Psychiatric Doctors",
    "services.team2": "Skilled Psychologists",
    "services.team3": "Full-time Physicians",
    "services.team4": "Experienced Nurses & Trained Health Workers",
    "services.service1.title": "Mental Health Treatment",
    "services.service1.description": "Comprehensive care for conditions including schizophrenia, depression, anxiety, bipolar disorder, and other mental health challenges.",
    "services.service1.feature1": "Individual Therapy",
    "services.service1.feature2": "Group Counseling",
    "services.service1.feature3": "Medication Management",
    "services.service1.feature4": "Crisis Intervention",
    "services.service2.title": "Drug Addiction Rehabilitation",
    "services.service2.description": "Specialized treatment programs for substance addictions including yaba, marijuana, phensedyl, heroin, and other dependencies.",
    "services.service2.feature1": "Detoxification",
    "services.service2.feature2": "Rehabilitation Programs",
    "services.service2.feature3": "Relapse Prevention",
    "services.service2.feature4": "Aftercare Support",
    "services.service3.title": "24/7 Emergency Care",
    "services.service3.description": "Round-the-clock emergency psychiatric services for crisis situations, suicidal thoughts, and acute mental health episodes.",
    "services.service3.feature1": "Crisis Hotline",
    "services.service3.feature2": "Emergency Admissions",
    "services.service3.feature3": "Immediate Assessment",
    "services.service3.feature4": "Rapid Response",
    "services.service4.title": "Psychiatric Consultation",
    "services.service4.description": "Expert evaluation and diagnosis by nationally and internationally renowned psychiatric doctors.",
    "services.service4.feature1": "Initial Assessment",
    "services.service4.feature2": "Diagnostic Evaluation",
    "services.service4.feature3": "Treatment Planning",
    "services.service4.feature4": "Follow-up Care",
    "services.service5.title": "Psychological Therapy",
    "services.service5.description": "Evidence-based therapeutic interventions delivered by skilled psychologists and mental health professionals.",
    "services.service5.feature1": "Cognitive Behavioral Therapy",
    "services.service5.feature2": "Psychotherapy",
    "services.service5.feature3": "Family Therapy",
    "services.service5.feature4": "Support Groups",
    "services.service6.title": "Rehabilitation Support",
    "services.service6.description": "Comprehensive rehabilitation services to help individuals rebuild their lives and achieve long-term recovery.",
    "services.service6.feature1": "Life Skills Training",
    "services.service6.feature2": "Vocational Support",
    "services.service6.feature3": "Social Integration",
    "services.service6.feature4": "Ongoing Monitoring",
    "services.condition1": "Schizophrenia",
    "services.condition2": "Suicidal Thoughts & Ideation",
    "services.condition3": "Hallucinations & Delusions",
    "services.condition4": "Depression & Anxiety Disorders",
    "services.condition5": "Bipolar Disorder",
    "services.condition6": "Substance Use Disorders",

    // Contact Page
    "contact.badge": "Contact us",
    "contact.title": "We're here to",
    "contact.titleHighlight": "listen, support & guide",
    "contact.description": "Reach out anytime if you or a loved one needs help. Our mental health team is available 24/7 for crisis care, admissions, and follow‑up queries — in a safe, confidential environment.",
    "contact.emergencyHelpline": "24/7 emergency helpline",
    "contact.confidential": "Strictly confidential conversations",
    "contact.kindStaff": "Kind, trauma‑informed staff",
    "contact.kindStaffDesc": "Every message is read by a trained mental health professional.",
    "contact.emergencySupport": "Emergency & 24/7 support",
    "contact.emergencyDesc": "If you are in immediate danger or experiencing a life‑threatening emergency, please contact your local emergency services right away.",
    "contact.helpline": "24/7 Helpline",
    "contact.crisisEmail": "Crisis Email",
    "contact.hospitalLocation": "Hospital location",
    "contact.visitingHours": "Visiting hours:",
    "contact.opd": "OPD:",
    "contact.sendMessage": "Send us a message",
    "contact.messageDesc": "Share a few details and our team will contact you within one business day. Please avoid sharing very sensitive information in this form.",
    "contact.fullName": "Full name",
    "contact.namePlaceholder": "Your name",
    "contact.phone": "Phone number",
    "contact.phonePlaceholder": "+880...",
    "contact.email": "Email address",
    "contact.emailPlaceholder": "you@example.com",
    "contact.reason": "Reason for contact",
    "contact.selectOption": "Select an option",
    "contact.appointment": "Appointment / OPD booking",
    "contact.inpatient": "In‑patient admission",
    "contact.emergencyFollowup": "Emergency follow‑up",
    "contact.generalEnquiry": "General enquiry",
    "contact.howCanWeHelp": "How can we help?",
    "contact.messagePlaceholder": "Briefly describe what you or your loved one is going through...",
    "contact.consent": "I understand this form is not for emergencies and consent to being contacted by Brain And Life Hospital regarding my enquiry.",
    "contact.submit": "Submit message",

    // About Page
    "about.badge": "About us",
    "about.title": "Compassionate care for",
    "about.titleHighlight": "mental wellness",
    "about.description": "At Brain And Life Hospital, we provide respectful, evidence‑based mental health care in a calm, supportive environment. Our goal is to restore hope, strengthen resilience, and help people return to meaningful daily life.",
    "about.supportReady": "24/7 support ready",
    "about.confidentialCare": "Confidential, patient-first care",
    "about.contactTeam": "Contact our team",
    "about.viewServices": "View services",
    "about.traumaCare": "Trauma‑informed, respectful care",
    "about.traumaDesc": "Every story is heard with dignity and empathy.",
    "about.mission": "Our mission",
    "about.missionDesc": "To deliver safe, ethical, and effective psychiatric care—through a blend of clinical expertise, therapeutic support, and human connection.",
    "about.expect": "What patients can expect",
    "about.clearAssessment": "Clear assessment & care plan",
    "about.stigmaFree": "Supportive, stigma‑free environment",
    "about.followups": "Follow‑ups and continuity of care",
    "about.compassionFirst": "Compassion first",
    "about.compassionDesc": "We meet every person with dignity, empathy, and respect—because healing starts with feeling safe.",
    "about.evidenceCare": "Evidence-based care",
    "about.evidenceDesc": "Our plans are guided by modern clinical practice and adjusted through ongoing assessment and outcomes.",
    "about.wholePerson": "Whole-person approach",
    "about.wholePersonDesc": "We support mind, body, family, and daily life—helping patients build stability beyond symptoms.",
    "about.emergencySupport": "Emergency support",
    "about.careTeams": "Care teams",
    "about.patientPrivacy": "Patient-first privacy",
    "about.treatmentPlans": "Treatment plans",
    "about.readyToTalk": "Ready to talk to someone?",
    "about.readyDesc": "If you're seeking support for yourself or a loved one, our team can guide you to the right care pathway.",
    "about.bookAppointment": "Book an appointment",
    "about.callHelpline": "Call 24/7 helpline",
    "about.multidisciplinary": "Multi‑disciplinary",
    "about.confidential": "Confidential",
    "about.personalized": "Personalized",

    // Treatment Page
    "treatment.badge": "Our Treatment Approach",
    "treatment.title": "Personalized, evidence-based",
    "treatment.titleHighlight": "mental health treatment",
    "treatment.description": "Comprehensive, individualized plans combining proven therapies with compassionate care to help you achieve lasting recovery and wellness.",
    "treatment.multidisciplinary": "24/7 multidisciplinary team",
    "treatment.traumaCare": "Trauma‑informed, respectful care",
    "treatment.traumaDesc": "Every plan honors dignity and safety.",
    "treatment.programs": "Programs",
    "treatment.modalities": "Treatment",
    "treatment.modalitiesHighlight": "Modalities",
    "treatment.modalitiesDesc": "A comprehensive range of therapeutic approaches tailored to your unique needs.",
    "treatment.journey": "Journey",
    "treatment.treatmentJourney": "Your Treatment",
    "treatment.journeyHighlight": "Journey",
    "treatment.journeyDesc": "A structured, step-by-step approach to recovery and wellness.",
    "treatment.evidence": "Evidence",
    "treatment.evidenceApproaches": "Evidence-Based",
    "treatment.evidenceHighlight": "Approaches",
    "treatment.evidenceDesc": "Grounded in scientific research and proven therapeutic methods.",
    "treatment.specializedPrograms": "Specialized",
    "treatment.programsHighlight": "Treatment Programs",
    "treatment.inpatient": "Inpatient Treatment",
    "treatment.inpatientDesc": "Intensive 24/7 care in a safe, structured environment for individuals requiring constant medical supervision and support.",
    "treatment.roundClock": "Round-the-clock medical care",
    "treatment.structured": "Structured daily programs",
    "treatment.safeEnvironment": "Safe, supportive environment",
    "treatment.outpatient": "Outpatient Treatment",
    "treatment.outpatientDesc": "Flexible treatment options that allow you to continue daily life while receiving comprehensive care and support.",
    "treatment.flexible": "Flexible scheduling",
    "treatment.maintainRoutines": "Maintain daily routines",
    "treatment.familySupport": "Family and work support",
    "treatment.beginJourney": "Begin Your Journey to Recovery",
    "treatment.beginDesc": "Take the first step toward better mental health. Our compassionate team is ready to create a personalized treatment plan tailored to your unique needs.",
    "treatment.scheduleConsultation": "Schedule Consultation",
    "treatment.callNow": "Call Now: 24/7 Helpline",
  },
  bn: {
    // Navigation
    "nav.home": "হোম",
    "nav.about": "আমাদের সম্পর্কে",
    "nav.services": "সেবা",
    "nav.treatment": "চিকিৎসা",
    "nav.contact": "যোগাযোগ",
    "nav.getHelp": "সাহায্য নিন",

    // Hero Section
    "hero.tagline": "সেরা মানসিক স্বাস্থ্য সমাধান",
    "hero.title": "ব্রেইন অ্যান্ড লাইফ হাসপাতাল",
    "hero.description": "আমরা একটি নিরাপদ, সহায়ক পরিবেশে সহানুভূতিশীল, প্রমাণ-ভিত্তিক মানসিক স্বাস্থ্য সেবা প্রদান করি—ব্যক্তিদের ভারসাম্য পুনরুদ্ধার, স্থিতিস্থাপকতা গড়ে তোলা এবং আশা পুনরায় আবিষ্কার করতে সাহায্য করি।",
    "hero.learnMore": "আরও জানুন",
    "hero.contactUs": "যোগাযোগ করুন",
    "hero.followUs": "আমাদের অনুসরণ করুন:",

    // MD Message
    "md.badge": "নেতৃত্ব থেকে একটি বার্তা",
    "md.title": "আমাদের ব্যবস্থাপনা পরিচালক কী বলেছেন শুনুন",
    "md.quote": "আমাদের হাসপাতালে, আমরা বিশ্বাস করি যে মানসিক স্বাস্থ্য সেবা সহানুভূতি দিয়ে শুরু হয়। আমাদের দরজা দিয়ে যে প্রতিটি ব্যক্তি আসেন তাকে মর্যাদা, বোঝাপড়া এবং সম্মানের সাথে আচরণ করা হয়। আমাদের প্রতিশ্রুতি কেবল মন নিরাময় করা নয়, বরং আশা, উদ্দেশ্য এবং জীবনের মান পুনরুদ্ধার করা।",
    "md.author": "— মোঃ ফকরুল হোসেন, ব্যবস্থাপনা পরিচালক, ব্রেইন অ্যান্ড লাইফ হাসপাতাল",
    "md.readMore": "আরও পড়ুন",

    // MD Page
    "mdPage.heroBadge": "ব্যবস্থাপনা পরিচালকের বার্তা",
    "mdPage.heroTitle": "মানসিক সুস্থতার জন্য সহানুভূতিশীল যত্ন",
    "mdPage.heroDescription": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে, আমরা বুঝতে পারি যে মানসিক স্বাস্থ্যের চ্যালেঞ্জগুলি কেবল ব্যক্তিদেরই প্রভাবিত করে না, বরং সমগ্র পরিবারকেও প্রভাবিত করে। আমাদের মিশন হল ব্যাপক, সহানুভূতিশীল যত্ন প্রদান করা যা পুনরুদ্ধার এবং নিরাময়কে সমর্থন করে।",
    "mdPage.section1Title": "মানসিক স্বাস্থ্যের চ্যালেঞ্জ বোঝা",
    "mdPage.section1Para1": "কাজের চাপ, পারিবারিক সমস্যা, সম্পর্কের বিষয় এবং অতীতের স্মৃতি অপ্রতিরোধ্য হয়ে উঠতে পারে—বিশেষ করে যখন আপনার যত্ন নেওয়ার জন্য সন্তান থাকে। যখন এই চ্যালেঞ্জগুলি সহ্য করা খুব কঠিন হয়ে যায়, তখন সেগুলি মানসিক স্বাস্থ্য সমস্যার দিকে নিয়ে যেতে পারে যার জন্য পেশাদার সহায়তা এবং চিকিৎসার প্রয়োজন।",
    "mdPage.section1Para2": "মাদক ব্যবহারের ব্যাধি আমাদের সমাজে একটি গুরুতর উদ্বেগ। যখন মাদকাসক্তি একটি পরিবারে প্রবেশ করে, এটি প্রত্যেককে প্রভাবিত করে—কেবল মাদকাসক্তির সাথে লড়াই করা ব্যক্তিকেই নয়। পরিবারগুলি প্রায়শই নিজেদেরকে অশান্তিতে খুঁজে পায়, তাদের প্রিয়জনদের কীভাবে সাহায্য করা যায় সে সম্পর্কে কঠিন সিদ্ধান্তের মুখোমুখি হয়।",
    "mdPage.section2Title": "আমাদের চিকিৎসা পদ্ধতি",
    "mdPage.section2Para1": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে, আমরা স্বীকার করি যে প্রতিটি রোগীর ব্যক্তিগতকৃত যত্নের প্রয়োজন। আমাদের চিকিৎসা পরিকল্পনা বিভিন্ন ধরনের কাউন্সেলিং এবং যত্নের প্রয়োজনের according to পরিবর্তিত হয়। আমরা বুঝতে পারি যে মাদকাসক্তি একটি রোগ যা চিকিৎসা হস্তক্ষেপ, মনস্তাত্ত্বিক সহায়তা এবং পরিবারের অংশগ্রহণের প্রয়োজন।",
    "mdPage.section2Para2": "দুর্ভাগ্যবশত, অনেক পরিবার এমন একটি বিন্দুতে পৌঁছায় যেখানে তারা মনে করে যে চিকিৎসা আর প্রয়োজনীয় বা কার্যকর নয়। কিছু পুনরাবৃত্ত পতনের কারণে আশা হারাতে পারে। পরিবারের সদস্যরা কখনও কখনও মাদকাসক্তির সাথে লড়াই করা ব্যক্তি থেকে নিজেদের দূরে সরিয়ে নেয়, যা অবহেলা এবং বিচ্ছিন্নতার অনুভূতির দিকে নিয়ে যেতে পারে—পুনরুদ্ধার প্রক্রিয়াকে আরও জটিল করে তোলে।",
    "mdPage.section3Title": "ব্যাপক ইনপেশেন্ট যত্ন",
    "mdPage.section3Para1": "নিবিড় চিকিৎসার প্রয়োজন এমন রোগীদের জন্য, আমাদের হাসপাতাল একটি নিরাপদ, সহায়ক পরিবেশ প্রদান করে। সাধারণত, রোগীরা আমাদের সাথে ১৫-৩০ দিন থাকেন, এই সময়ে তারা চিকিৎসা, থেরাপি এবং পরিবার কাউন্সেলিং সহ ব্যাপক যত্ন পান।",
    "mdPage.section3Para2": "আমরা বিশ্বাস করি যে পুনরুদ্ধার পুরো পরিবারকে জড়িত করে। আমাদের পদ্ধতি পরিবারের সংযোগ পুনর্নির্মাণ এবং নিশ্চিত করে যে রোগী এবং তাদের পরিবারের সদস্যরা উভয়ই তাদের প্রয়োজনীয় সহায়তা পান। নিয়মিত ওষুধ ব্যবস্থাপনা এবং চলমান থেরাপি চিকিৎসার অপরিহার্য উপাদান, কারণ এগুলি পতন রোধ করতে এবং দীর্ঘমেয়াদী পুনরুদ্ধারকে সমর্থন করতে সাহায্য করে।",
    "mdPage.section4Title": "দীর্ঘমেয়াদী পুনরুদ্ধার সহায়তা",
    "mdPage.section4Para1": "পুনরুদ্ধার একটি চলমান যাত্রা যা হাসপাতালে থাকার বাইরে প্রসারিত। ছাড়ার পর, রোগীদের তাদের অগ্রগতি বজায় রাখার জন্য অব্যাহত সহায়তার প্রয়োজন। এর মধ্যে পুরানো বন্ধু এবং পরিবেশ থেকে দূরে থাকা অন্তর্ভুক্ত যা পতনকে ট্রিগার করতে পারে, এবং নতুন, স্বাস্থ্যকর সম্পর্ক এবং রুটিন গড়ে তোলা।",
    "mdPage.section4Para2": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে, আমরা স্থায়ী পুনরুদ্ধারের জন্য প্রয়োজনীয় সহায়তা এবং যত্ন প্রদানের জন্য প্রতিশ্রুতিবদ্ধ। আমাদের দল রোগী এবং তাদের পরিবারকে নিরাময় এবং সুস্থতার পথে নেভিগেট করতে সাহায্য করার জন্য অক্লান্ত পরিশ্রম করে।",
    "mdPage.ctaTitle": "সহায়তা প্রয়োজন?",
    "mdPage.ctaDescription": "আপনি বা আপনার প্রিয়জনের যদি সাহায্যের প্রয়োজন হয়, আমাদের সহানুভূতিশীল দল আপনাকে নির্দেশনা দেওয়ার জন্য এখানে রয়েছে।",
    "mdPage.contactUs": "যোগাযোগ করুন",
    "mdPage.viewServices": "সেবা দেখুন",

    // Specialists
    "specialists.badge": "আমাদের বিশেষজ্ঞ দল",
    "specialists.title": "আমাদের বিশেষজ্ঞ মনোরোগ বিশেষজ্ঞদের সাথে পরিচিত হন",
    "specialists.description": "মনোরোগবিদ্যা এবং সাইকোথেরাপিতে জাতীয়ভাবে স্বীকৃত পরামর্শদাতা, সহানুভূতিশীল, প্রমাণ-ভিত্তিক মানসিক স্বাস্থ্য সেবার জন্য নিবেদিত।",
    "specialists.readMore": "আরও পড়ুন",
    "specialists.mohit.name": "প্রফেসর ড. মোহিত",
    "specialists.mohit.lastName": "কামাল",
    "specialists.mohit.description": "প্রফেসর ড. এম এ মোহিত কামাল একজন বিশিষ্ট মনোরোগ বিশেষজ্ঞ এবং সাইকোথেরাপিস্ট যার মানসিক স্বাস্থ্য সেবায় ব্যাপক অভিজ্ঞতা রয়েছে। ল্যাবএইড কার্ডিয়াক হাসপাতালে সিনিয়র চিফ কনসালট্যান্ট হিসেবে, তিনি ব্যাপক মনোরোগবিদ্যা সেবা এবং সাইকোথেরাপি সেবা প্রদান করেন।",
    "specialists.rabbani.name": "প্রফেসর ড. গোলাম",
    "specialists.rabbani.lastName": "রব্বানী",
    "specialists.rabbani.description": "প্রফেসর ড. গোলাম রব্বানী একজন বিশিষ্ট মনোরোগ বিশেষজ্ঞ এবং মানসিক স্বাস্থ্য বিশেষজ্ঞ যার মনোরোগবিদ্যা সেবা এবং সাইকোথেরাপিতে ব্যাপক অভিজ্ঞতা রয়েছে। ব্রেইন অ্যান্ড লাইফ হাসপাতালে চিফ কনসালট্যান্ট হিসেবে, তিনি রোগী-কেন্দ্রিক পদ্ধতি এবং প্রমাণ-ভিত্তিক চিকিৎসা সহ ব্যাপক মানসিক স্বাস্থ্য সেবা প্রদান করেন।",
    "specialists.mandal.name": "প্রফেসর ড. মহাদেব চন্দ্র",
    "specialists.mandal.lastName": "মণ্ডল",
    "specialists.mandal.description": "প্রফেসর ড. মহাদেব চন্দ্র মণ্ডল একজন খ্যাতিমান মনোরোগ বিশেষজ্ঞ এবং মানসিক স্বাস্থ্য বিশেষজ্ঞ যার ক্লিনিকাল মনোরোগবিদ্যা এবং সাইকোথেরাপিতে ব্যাপক অভিজ্ঞতা রয়েছে। ব্রেইন অ্যান্ড লাইফ হাসপাতালে সিনিয়র কনসালট্যান্ট হিসেবে, তিনি প্রমাণ-ভিত্তিক চিকিৎসা এবং রোগী পুনরুদ্ধারের উপর ফোকাস সহ ব্যাপক মানসিক স্বাস্থ্য সেবায় বিশেষজ্ঞ।",

    // Specialist Detail Pages - Common
    "specialistDetail.chiefConsultant": "চিফ কনসালট্যান্ট",
    "specialistDetail.seniorChiefConsultant": "সিনিয়র চিফ কনসালট্যান্ট",
    "specialistDetail.seniorConsultant": "সিনিয়র কনসালট্যান্ট",
    "specialistDetail.qualifications": "যোগ্যতা",
    "specialistDetail.currentPosition": "বর্তমান পদ",
    "specialistDetail.about": "সম্পর্কে",
    "specialistDetail.experience": "অভিজ্ঞতা",
    "specialistDetail.professionalExperience": "পেশাদার অভিজ্ঞতা",
    "specialistDetail.currentRoles": "বর্তমান ভূমিকা",
    "specialistDetail.previousPositions": "পূর্ববর্তী পদ",
    "specialistDetail.expertise": "দক্ষতা",
    "specialistDetail.areasOfExpertise": "দক্ষতার ক্ষেত্র",

    // Rabbani Detail Page
    "specialistDetail.rabbani.title": "চিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)",
    "specialistDetail.rabbani.qualifications": "এমবিবিএস: রাজশাহী মেডিকেল কলেজ, রাজশাহী বিশ্ববিদ্যালয়, বাংলাদেশ\nএফসিপিএস: বাংলাদেশ কলেজ অফ ফিজিশিয়ানস অ্যান্ড সার্জনস",
    "specialistDetail.rabbani.currentPosition": "মনোরোগবিদ্যার অধ্যাপক\nচিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)\nব্রেইন অ্যান্ড লাইফ হাসপাতাল",
    "specialistDetail.rabbani.aboutTitle": "ড. গোলাম রব্বানী সম্পর্কে",
    "specialistDetail.rabbani.about1": "প্রফেসর ড. গোলাম রব্বানী একজন বিশিষ্ট মনোরোগ বিশেষজ্ঞ এবং মানসিক স্বাস্থ্য বিশেষজ্ঞ যার মনোরোগবিদ্যা সেবা এবং সাইকোথেরাপিতে ব্যাপক অভিজ্ঞতা রয়েছে। ব্রেইন অ্যান্ড লাইফ হাসপাতালে চিফ কনসালট্যান্ট হিসেবে, তিনি রোগী-কেন্দ্রিক পদ্ধতি এবং প্রমাণ-ভিত্তিক চিকিৎসা সহ ব্যাপক মানসিক স্বাস্থ্য সেবা প্রদান করেন।",
    "specialistDetail.rabbani.about2": "রাজশাহী মেডিকেল কলেজ থেকে এমবিবিএস এবং বাংলাদেশ কলেজ অফ ফিজিশিয়ানস অ্যান্ড সার্জনস থেকে এফসিপিএস সহ উন্নত যোগ্যতার সাথে, ড. রব্বানী বিভিন্ন মানসিক স্বাস্থ্য অবস্থা নির্ণয় এবং চিকিৎসায় দশকের অভিজ্ঞতা নিয়ে আসেন। তার দক্ষতা ওষুধ চিকিৎসার সাথে সাইকোথেরাপিকে একত্রিত করে, রোগীদের জন্য সামগ্রিক যত্ন নিশ্চিত করে।",
    "specialistDetail.rabbani.currentRole1": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে মনোরোগবিদ্যার অধ্যাপক",
    "specialistDetail.rabbani.currentRole2": "চিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)",
    "specialistDetail.rabbani.currentRole3": "মানসিক স্বাস্থ্য গবেষণা বিভাগের প্রধান",
    "specialistDetail.rabbani.previousRole1": "ঢাকা মেডিকেল কলেজ হাসপাতালে সিনিয়র কনসালট্যান্ট মনোরোগ বিশেষজ্ঞ",
    "specialistDetail.rabbani.previousRole2": "ঢাকা বিশ্ববিদ্যালয়ে মনোরোগবিদ্যার সহযোগী অধ্যাপক",
    "specialistDetail.rabbani.previousRole3": "মানসিক স্বাস্থ্য ইনস্টিটিউট বাংলাদেশের ক্লিনিকাল পরিচালক",
    "specialistDetail.rabbani.previousRole4": "ডব্লিউএইচও মানসিক স্বাস্থ্য প্রোগ্রামে গবেষণা ফেলো",
    "specialistDetail.rabbani.expertise1": "ক্লিনিকাল মনোরোগবিদ্যা",
    "specialistDetail.rabbani.expertise1Desc": "ব্যাপক মনোরোগবিদ্যা নির্ণয় এবং চিকিৎসা",
    "specialistDetail.rabbani.expertise2": "সাইকোথেরাপি",
    "specialistDetail.rabbani.expertise2Desc": "কগনিটিভ বিহেভিওরাল থেরাপি এবং কাউন্সেলিং",
    "specialistDetail.rabbani.expertise3": "মানসিক স্বাস্থ্য গবেষণা",
    "specialistDetail.rabbani.expertise3Desc": "ক্লিনিকাল গবেষণা এবং প্রমাণ-ভিত্তিক অনুশীলন",

    // Mohit Detail Page
    "specialistDetail.mohit.title": "সিনিয়র চিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও সাইকোথেরাপি)",
    "specialistDetail.mohit.qualifications": "এমবিবিএস\nএম.ফিল. (মনোরোগবিদ্যা)\nএফসিপিএস (মনোরোগবিদ্যা)",
    "specialistDetail.mohit.currentPosition": "সাইকোথেরাপির অধ্যাপক\nসিনিয়র চিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও সাইকোথেরাপি)\nল্যাবএইড কার্ডিয়াক হাসপাতাল",
    "specialistDetail.mohit.aboutTitle": "ড. এম এ মোহিত কামাল সম্পর্কে",
    "specialistDetail.mohit.about1": "প্রফেসর ড. এম এ মোহিত কামাল একজন বিশিষ্ট মনোরোগ বিশেষজ্ঞ এবং সাইকোথেরাপিস্ট যার মানসিক স্বাস্থ্য সেবায় ব্যাপক অভিজ্ঞতা রয়েছে। ল্যাবএইড কার্ডিয়াক হাসপাতালে সিনিয়র চিফ কনসালট্যান্ট হিসেবে, তিনি ব্যাপক মনোরোগবিদ্যা সেবা এবং সাইকোথেরাপি সেবা প্রদান করেন।",
    "specialistDetail.mohit.about2": "এমবিবিএস, মনোরোগবিদ্যায় এম.ফিল., এবং মনোরোগবিদ্যায় এফসিপিএস সহ তার উন্নত যোগ্যতার সাথে, ড. কামাল তার অনুশীলনে জ্ঞান এবং দক্ষতার সম্পদ নিয়ে আসেন। মানসিক স্বাস্থ্যের প্রতি তার প্রতিশ্রুতি ক্লিনিকাল অনুশীলনের বাইরে একাডেমিক নেতৃত্ব এবং প্রাতিষ্ঠানিক উন্নয়নে প্রসারিত।",
    "specialistDetail.mohit.currentRole1": "সাইকোথেরাপির অধ্যাপক",
    "specialistDetail.mohit.currentRole2": "ল্যাবএইড কার্ডিয়াক হাসপাতালে সিনিয়র চিফ কনসালট্যান্ট (মনোরোগবিদ্যা ও সাইকোথেরাপি)",
    "specialistDetail.mohit.previousRole1": "সাবেক সাইকোথেরাপি প্রধান",
    "specialistDetail.mohit.previousRole2": "সাবেক একাডেমিক কোর্স পরিচালক এমডি (মনোরোগবিদ্যা)",
    "specialistDetail.mohit.previousRole3": "সাবেক পরিচালক, জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউট, ঢাকা",
    "specialistDetail.mohit.expertise1": "মনোরোগবিদ্যা",
    "specialistDetail.mohit.expertise1Desc": "ব্যাপক মনোরোগবিদ্যা নির্ণয় এবং চিকিৎসা",
    "specialistDetail.mohit.expertise2": "সাইকোথেরাপি",
    "specialistDetail.mohit.expertise2Desc": "প্রমাণ-ভিত্তিক থেরাপিউটিক হস্তক্ষেপ",
    "specialistDetail.mohit.expertise3": "একাডেমিক নেতৃত্ব",
    "specialistDetail.mohit.expertise3Desc": "চিকিৎসা শিক্ষা এবং প্রশিক্ষণ",

    // Mandal Detail Page
    "specialistDetail.mandal.title": "সিনিয়র কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)",
    "specialistDetail.mandal.qualifications": "এমবিবিএস\nএমডি (মনোরোগবিদ্যা)\nএফসিপিএস (মনোরোগবিদ্যা)",
    "specialistDetail.mandal.currentPosition": "মনোরোগবিদ্যার অধ্যাপক\nসিনিয়র কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)\nব্রেইন অ্যান্ড লাইফ হাসপাতাল",
    "specialistDetail.mandal.aboutTitle": "ড. মহাদেব চন্দ্র মণ্ডল সম্পর্কে",
    "specialistDetail.mandal.about1": "প্রফেসর ড. মহাদেব চন্দ্র মণ্ডল একজন খ্যাতিমান মনোরোগ বিশেষজ্ঞ এবং মানসিক স্বাস্থ্য বিশেষজ্ঞ যার ক্লিনিকাল মনোরোগবিদ্যা এবং সাইকোথেরাপিতে ব্যাপক অভিজ্ঞতা রয়েছে। ব্রেইন অ্যান্ড লাইফ হাসপাতালে সিনিয়র কনসালট্যান্ট হিসেবে, তিনি প্রমাণ-ভিত্তিক চিকিৎসা এবং রোগী পুনরুদ্ধারের উপর ফোকাস সহ ব্যাপক মানসিক স্বাস্থ্য সেবায় বিশেষজ্ঞ।",
    "specialistDetail.mandal.about2": "এমবিবিএস, মনোরোগবিদ্যায় এমডি, এবং মনোরোগবিদ্যায় এফসিপিএস সহ উন্নত যোগ্যতার সাথে, ড. মণ্ডল জটিল মানসিক স্বাস্থ্য অবস্থা নির্ণয় এবং চিকিৎসায় বছরের ক্লিনিকাল অভিজ্ঞতা নিয়ে আসেন। তার পদ্ধতি আধুনিক মনোরোগবিদ্যা অনুশীলনকে সহানুভূতিশীল যত্নের সাথে একত্রিত করে, বিভিন্ন মানসিক স্বাস্থ্য চ্যালেঞ্জ সহ রোগীদের জন্য সর্বোত্তম ফলাফল নিশ্চিত করে।",
    "specialistDetail.mandal.currentRole1": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে মনোরোগবিদ্যার অধ্যাপক",
    "specialistDetail.mandal.currentRole2": "সিনিয়র কনসালট্যান্ট (মনোরোগবিদ্যা ও মানসিক স্বাস্থ্য)",
    "specialistDetail.mandal.currentRole3": "মনোরোগবিদ্যা রেসিডেন্টদের জন্য ক্লিনিকাল সুপারভাইজার",
    "specialistDetail.mandal.previousRole1": "জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউটে কনসালট্যান্ট মনোরোগ বিশেষজ্ঞ",
    "specialistDetail.mandal.previousRole2": "বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয়ে মনোরোগবিদ্যার সহযোগী অধ্যাপক",
    "specialistDetail.mandal.previousRole3": "ঢাকা মেডিকেল কলেজ হাসপাতালে সিনিয়র মনোরোগ বিশেষজ্ঞ",
    "specialistDetail.mandal.previousRole4": "স্বাস্থ্য মন্ত্রণালয়ের মানসিক স্বাস্থ্য বিভাগে মেডিকেল অফিসার",
    "specialistDetail.mandal.expertise1": "প্রাপ্তবয়স্ক মনোরোগবিদ্যা",
    "specialistDetail.mandal.expertise1Desc": "মুড ডিসঅর্ডার এবং উদ্বেগ অবস্থার চিকিৎসা",
    "specialistDetail.mandal.expertise2": "কগনিটিভ থেরাপি",
    "specialistDetail.mandal.expertise2Desc": "কগনিটিভ বিহেভিওরাল থেরাপি এবং মাইন্ডফুলনেস-ভিত্তিক হস্তক্ষেপ",
    "specialistDetail.mandal.expertise3": "চিকিৎসা শিক্ষা",
    "specialistDetail.mandal.expertise3Desc": "মনোরোগবিদ্যা রেসিডেন্টদের প্রশিক্ষণ এবং তত্ত্বাবধান",

    // Steps
    "steps.badge": "দ্রুততম সমাধান",
    "steps.title": "৪টি সহজ ধাপে আপনার সমাধান পান",
    "steps.step1.title": "আপনি কী করছেন তা শেয়ার করুন",
    "steps.step1.desc": "আমাদের কল করুন বা আপনার মেজাজ, চিন্তা বা আচরণ সম্পর্কে কয়েকটি বিবরণ সহ একটি বার্তা পাঠান যাতে আমাদের দল বুঝতে পারে কীভাবে আপনাকে সর্বোত্তম সহায়তা করা যায়।",
    "steps.step2.title": "একজন বিশেষজ্ঞের সাথে দেখা করুন",
    "steps.step2.desc": "আপনার ইতিহাস, উদ্বেগ এবং লক্ষ্য নিয়ে আলোচনা করার জন্য আমাদের একজন মনোরোগ বিশেষজ্ঞ বা মনোবিজ্ঞানীর সাথে আপনার একটি গোপন পরামর্শ হবে।",
    "steps.step3.title": "আপনার চিকিৎসা পরিকল্পনা পান",
    "steps.step3.desc": "একসাথে আমরা একটি ব্যক্তিগতকৃত পরিকল্পনা তৈরি করি যা থেরাপি, ওষুধ, পুনর্বাসন বা আপনার জীবনের সাথে মানানসই পদ্ধতির সংমিশ্রণ অন্তর্ভুক্ত করতে পারে।",
    "steps.step4.title": "চলমান সহায়তার সাথে যত্ন শুরু করুন",
    "steps.step4.desc": "নিয়মিত ফলো-আপ, পরিবারের নির্দেশনা এবং ২৪/৭ সহায়তার সাথে আপনার চিকিৎসা শুরু করুন যাতে আপনি আপনার পুনরুদ্ধারের যাত্রায় কখনই একা অনুভব না করেন।",

    // Doctors
    "doctors.badge": "আমাদের চিকিৎসা দল",
    "doctors.title": "আমাদের সহানুভূতিশীল ডাক্তারদের সাথে পরিচিত হন",
    "doctors.description": "আমাদের দক্ষ চিকিৎসা পেশাদাররা ২৪/৭ যত্ন প্রদান করে, চিকিৎসা দক্ষতা এবং সহানুভূতিকে একত্রিত করে তাদের মানসিক স্বাস্থ্য যাত্রার প্রতিটি ধাপে রোগীদের সহায়তা করে।",

    // Staff
    "staff.badge": "আমাদের দল",
    "staff.title": "কেন ব্রেইন অ্যান্ড লাইফ বেছে নিন",
    "staff.description": "আমাদের আধুনিক পদ্ধতি এবং নিবেদিত পেশাদারদের সাথে মানসিক স্বাস্থ্য সেবায় উৎকর্ষতা অনুভব করুন।",

    // CTA
    "cta.title": "প্রথম পদক্ষেপ নিতে প্রস্তুত?",
    "cta.description": "আমাদের সহানুভূতিশীল দল আপনার বা আপনার প্রিয়জনের পুনরুদ্ধার এবং সুস্থতার দিকে যাত্রা শুরু করতে সাহায্য করতে এখানে রয়েছে।",
    "cta.contact": "আজই যোগাযোগ করুন",
    "cta.call": "২৪/৭ হেল্পলাইন কল করুন",

    // Footer
    "footer.tagline": "আমরা বাড়ি থেকে রোগী নিয়ে আসি এবং উপস্থিতির প্রয়োজন নেই।",
    "footer.description": "একটি নিরাপদ এবং সহায়ক পরিবেশে সহানুভূতিশীল, প্রমাণ-ভিত্তিক মানসিক স্বাস্থ্য সেবা প্রদান করা।",
    "footer.navigation": "নেভিগেশন",
    "footer.contact": "যোগাযোগ",
    "footer.followUs": "আমাদের অনুসরণ করুন",
    "footer.socialDesc": "সামাজিক মিডিয়ায় আমাদের সাথে সংযুক্ত থাকুন",
    "footer.copyright": "সমস্ত অধিকার সংরক্ষিত।",
    "footer.madeWith": "তৈরি করা হয়েছে",
    "footer.for": "মানসিক সুস্থতার জন্য",

    // Hero banner text
    "hero.banner": "সহানুভূতিশীল, প্রমাণ-ভিত্তিক যত্ন",
    "hero.bannerSub": "আপনার সুস্থতার যাত্রা এখান থেকে শুরু হয়।",

    // Services Page
    "services.badge": "আমাদের সেবা",
    "services.title": "সহানুভূতিশীল মানসিক স্বাস্থ্য ও",
    "services.titleHighlight": "মাদকাসক্তি যত্ন",
    "services.description": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে, আমরা প্রমাণ-ভিত্তিক চিকিৎসার সাথে একটি শান্ত, চিকিৎসামূলক পরিবেশকে একত্রিত করি। আমাদের বহু-শৃঙ্খলাবদ্ধ দল আপনাকে ২৪/৭ সহায়তা করে—সংকট, পুনরুদ্ধার এবং দীর্ঘমেয়াদী সুস্থতার মাধ্যমে।",
    "services.bookConsultation": "গোপন পরামর্শ বুক করুন",
    "services.emergencySupport": "২৪/৭ জরুরি সহায়তা",
    "services.emergencySupportDesc": "মানসিক স্বাস্থ্য এবং মাদকাসক্তি সংকটের জন্য সর্বদা সক্রিয় যত্ন।",
    "services.emergencyCare": "জরুরি যত্ন",
    "services.holisticSupport": "সামগ্রিক সহায়তা",
    "services.safeEnvironment": "শান্ত পরিবেশ",
    "services.programs": "প্রোগ্রাম",
    "services.specializedServices": "বিশেষায়িত সেবা",
    "services.specializedDesc": "প্রতিটি ব্যক্তির প্রয়োজনের জন্য তৈরি করা ব্যাপক চিকিৎসা প্রোগ্রাম—সহানুভূতি, নিরাপত্তা এবং দক্ষতার সাথে প্রদান করা।",
    "services.expertise": "দক্ষতা",
    "services.conditionsWeTreat": "আমরা যে অবস্থাগুলিতে",
    "services.conditionsHighlight": "বিশেষজ্ঞ",
    "services.conditionsDesc": "বিভিন্ন ধরনের মানসিক স্বাস্থ্য অবস্থা এবং পদার্থ ব্যবহারের ব্যাধির জন্য সহানুভূতিশীল যত্ন।",
    "services.team": "দল",
    "services.expertTeam": "বিশেষজ্ঞ দল",
    "services.confidentialCare": "গোপন, বিচার-মুক্ত যত্ন",
    "services.confidentialDesc": "প্রতিটি যাত্রাকে মর্যাদা এবং সম্মানের সাথে আচরণ করা হয়।",
    "services.emergencyServices": "২৪/৭ জরুরি ও সহায়তা সেবা",
    "services.emergencyDesc": "মানসিক স্বাস্থ্য সংকট ব্যবসায়িক ঘন্টার জন্য অপেক্ষা করে না। আমাদের নিবেদিত দল দিনরাত উপলব্ধ তাৎক্ষণিক যত্ন, সহায়তা এবং হস্তক্ষেপ প্রদানের জন্য যখন আপনার সবচেয়ে বেশি প্রয়োজন।",
    "services.crisisHotline": "সংকট হটলাইন",
    "services.immediate": "তাৎক্ষণিক",
    "services.immediateResponse": "জরুরি প্রতিক্রিয়া",
    "services.expert": "বিশেষজ্ঞ",
    "services.safe": "নিরাপদ",
    "services.our": "আমাদের",
    "services.team1": "জাতীয় ও আন্তর্জাতিকভাবে খ্যাতিমান মনোরোগ বিশেষজ্ঞ ডাক্তার",
    "services.team2": "দক্ষ মনোবিজ্ঞানী",
    "services.team3": "পূর্ণকালীন চিকিৎসক",
    "services.team4": "অভিজ্ঞ নার্স ও প্রশিক্ষিত স্বাস্থ্যকর্মী",
    "services.service1.title": "মানসিক স্বাস্থ্য চিকিৎসা",
    "services.service1.description": "স্কিজোফ্রেনিয়া, বিষণ্নতা, উদ্বেগ, বাইপোলার ডিসঅর্ডার এবং অন্যান্য মানসিক স্বাস্থ্য চ্যালেঞ্জ সহ অবস্থার জন্য ব্যাপক যত্ন।",
    "services.service1.feature1": "ব্যক্তিগত থেরাপি",
    "services.service1.feature2": "গ্রুপ কাউন্সেলিং",
    "services.service1.feature3": "ওষুধ ব্যবস্থাপনা",
    "services.service1.feature4": "সংকট হস্তক্ষেপ",
    "services.service2.title": "মাদকাসক্তি পুনর্বাসন",
    "services.service2.description": "ইয়াবা, গাঁজা, ফেনসিডিল, হেরোইন এবং অন্যান্য নির্ভরতার জন্য বিশেষায়িত চিকিৎসা প্রোগ্রাম।",
    "services.service2.feature1": "ডিটক্সিফিকেশন",
    "services.service2.feature2": "পুনর্বাসন প্রোগ্রাম",
    "services.service2.feature3": "পুনরাবৃত্তি প্রতিরোধ",
    "services.service2.feature4": "আফটারকেয়ার সহায়তা",
    "services.service3.title": "২৪/৭ জরুরি যত্ন",
    "services.service3.description": "সংকট পরিস্থিতি, আত্মহত্যার চিন্তা এবং তীব্র মানসিক স্বাস্থ্য পর্বের জন্য দিনরাত জরুরি মনোরোগবিদ্যা সেবা।",
    "services.service3.feature1": "সংকট হটলাইন",
    "services.service3.feature2": "জরুরি ভর্তি",
    "services.service3.feature3": "তাৎক্ষণিক মূল্যায়ন",
    "services.service3.feature4": "দ্রুত প্রতিক্রিয়া",
    "services.service4.title": "মনোরোগবিদ্যা পরামর্শ",
    "services.service4.description": "জাতীয় ও আন্তর্জাতিকভাবে খ্যাতিমান মনোরোগ বিশেষজ্ঞ ডাক্তারদের দ্বারা বিশেষজ্ঞ মূল্যায়ন এবং রোগ নির্ণয়।",
    "services.service4.feature1": "প্রাথমিক মূল্যায়ন",
    "services.service4.feature2": "রোগ নির্ণয় মূল্যায়ন",
    "services.service4.feature3": "চিকিৎসা পরিকল্পনা",
    "services.service4.feature4": "ফলো-আপ যত্ন",
    "services.service5.title": "মনস্তাত্ত্বিক থেরাপি",
    "services.service5.description": "দক্ষ মনোবিজ্ঞানী এবং মানসিক স্বাস্থ্য পেশাদারদের দ্বারা প্রদত্ত প্রমাণ-ভিত্তিক চিকিৎসামূলক হস্তক্ষেপ।",
    "services.service5.feature1": "কগনিটিভ বিহেভিওরাল থেরাপি",
    "services.service5.feature2": "সাইকোথেরাপি",
    "services.service5.feature3": "পরিবার থেরাপি",
    "services.service5.feature4": "সাপোর্ট গ্রুপ",
    "services.service6.title": "পুনর্বাসন সহায়তা",
    "services.service6.description": "ব্যক্তিদের তাদের জীবন পুনর্গঠন করতে এবং দীর্ঘমেয়াদী পুনরুদ্ধার অর্জনে সাহায্য করার জন্য ব্যাপক পুনর্বাসন সেবা।",
    "services.service6.feature1": "জীবন দক্ষতা প্রশিক্ষণ",
    "services.service6.feature2": "পেশাগত সহায়তা",
    "services.service6.feature3": "সামাজিক একীকরণ",
    "services.service6.feature4": "চলমান পর্যবেক্ষণ",
    "services.condition1": "স্কিজোফ্রেনিয়া",
    "services.condition2": "আত্মহত্যার চিন্তা ও ধারণা",
    "services.condition3": "হ্যালুসিনেশন ও বিভ্রম",
    "services.condition4": "বিষণ্নতা ও উদ্বেগ ব্যাধি",
    "services.condition5": "বাইপোলার ডিসঅর্ডার",
    "services.condition6": "পদার্থ ব্যবহারের ব্যাধি",

    // Contact Page
    "contact.badge": "যোগাযোগ করুন",
    "contact.title": "আমরা এখানে আছি",
    "contact.titleHighlight": "শুনতে, সহায়তা করতে এবং নির্দেশনা দিতে",
    "contact.description": "আপনার বা আপনার প্রিয়জনের সাহায্যের প্রয়োজন হলে যেকোনো সময় যোগাযোগ করুন। আমাদের মানসিক স্বাস্থ্য দল সংকট যত্ন, ভর্তি এবং ফলো-আপ প্রশ্নের জন্য ২৪/৭ উপলব্ধ — একটি নিরাপদ, গোপন পরিবেশে।",
    "contact.emergencyHelpline": "২৪/৭ জরুরি হেল্পলাইন",
    "contact.confidential": "কঠোরভাবে গোপন কথোপকথন",
    "contact.kindStaff": "দয়ালু, আঘাত-সচেতন কর্মী",
    "contact.kindStaffDesc": "প্রতিটি বার্তা একজন প্রশিক্ষিত মানসিক স্বাস্থ্য পেশাদার দ্বারা পড়া হয়।",
    "contact.emergencySupport": "জরুরি ও ২৪/৭ সহায়তা",
    "contact.emergencyDesc": "আপনি যদি তাৎক্ষণিক বিপদে থাকেন বা জীবন-হুমকির জরুরি অবস্থা অনুভব করছেন, অনুগ্রহ করে অবিলম্বে আপনার স্থানীয় জরুরি সেবার সাথে যোগাযোগ করুন।",
    "contact.helpline": "২৪/৭ হেল্পলাইন",
    "contact.crisisEmail": "সংকট ইমেইল",
    "contact.hospitalLocation": "হাসপাতালের অবস্থান",
    "contact.visitingHours": "দেখার সময়:",
    "contact.opd": "ওপিডি:",
    "contact.sendMessage": "আমাদের একটি বার্তা পাঠান",
    "contact.messageDesc": "কয়েকটি বিবরণ শেয়ার করুন এবং আমাদের দল এক ব্যবসায়িক দিনের মধ্যে আপনার সাথে যোগাযোগ করবে। অনুগ্রহ করে এই ফর্মে খুব সংবেদনশীল তথ্য শেয়ার করা এড়িয়ে চলুন।",
    "contact.fullName": "পূর্ণ নাম",
    "contact.namePlaceholder": "আপনার নাম",
    "contact.phone": "ফোন নম্বর",
    "contact.phonePlaceholder": "+৮৮০...",
    "contact.email": "ইমেইল ঠিকানা",
    "contact.emailPlaceholder": "you@example.com",
    "contact.reason": "যোগাযোগের কারণ",
    "contact.selectOption": "একটি বিকল্প নির্বাচন করুন",
    "contact.appointment": "অ্যাপয়েন্টমেন্ট / ওপিডি বুকিং",
    "contact.inpatient": "ইন‑পেশেন্ট ভর্তি",
    "contact.emergencyFollowup": "জরুরি ফলো‑আপ",
    "contact.generalEnquiry": "সাধারণ জিজ্ঞাসা",
    "contact.howCanWeHelp": "আমরা কীভাবে সাহায্য করতে পারি?",
    "contact.messagePlaceholder": "সংক্ষেপে বর্ণনা করুন আপনি বা আপনার প্রিয়জন কী করছেন...",
    "contact.consent": "আমি বুঝতে পারছি যে এই ফর্মটি জরুরি অবস্থার জন্য নয় এবং আমার জিজ্ঞাসা সম্পর্কে ব্রেইন অ্যান্ড লাইফ হাসপাতালের সাথে যোগাযোগের জন্য সম্মতি দিচ্ছি।",
    "contact.submit": "বার্তা জমা দিন",

    // About Page
    "about.badge": "আমাদের সম্পর্কে",
    "about.title": "জন্য সহানুভূতিশীল যত্ন",
    "about.titleHighlight": "মানসিক সুস্থতা",
    "about.description": "ব্রেইন অ্যান্ড লাইফ হাসপাতালে, আমরা একটি শান্ত, সহায়ক পরিবেশে সম্মানজনক, প্রমাণ-ভিত্তিক মানসিক স্বাস্থ্য সেবা প্রদান করি। আমাদের লক্ষ্য হল আশা পুনরুদ্ধার করা, স্থিতিস্থাপকতা শক্তিশালী করা এবং মানুষকে অর্থপূর্ণ দৈনন্দিন জীবনে ফিরিয়ে আনা।",
    "about.supportReady": "২৪/৭ সহায়তা প্রস্তুত",
    "about.confidentialCare": "গোপন, রোগী-প্রথম যত্ন",
    "about.contactTeam": "আমাদের দলের সাথে যোগাযোগ করুন",
    "about.viewServices": "সেবা দেখুন",
    "about.traumaCare": "আঘাত-সচেতন, সম্মানজনক যত্ন",
    "about.traumaDesc": "প্রতিটি গল্প মর্যাদা এবং সহানুভূতির সাথে শোনা হয়।",
    "about.mission": "আমাদের মিশন",
    "about.missionDesc": "নিরাপদ, নৈতিক এবং কার্যকর মনোরোগবিদ্যা সেবা প্রদান করা—ক্লিনিকাল দক্ষতা, চিকিৎসামূলক সহায়তা এবং মানবিক সংযোগের মিশ্রণের মাধ্যমে।",
    "about.expect": "রোগীরা কী আশা করতে পারে",
    "about.clearAssessment": "স্পষ্ট মূল্যায়ন ও যত্ন পরিকল্পনা",
    "about.stigmaFree": "সহায়ক, কলঙ্ক-মুক্ত পরিবেশ",
    "about.followups": "ফলো‑আপ এবং যত্নের ধারাবাহিকতা",
    "about.compassionFirst": "প্রথমে সহানুভূতি",
    "about.compassionDesc": "আমরা প্রতিটি ব্যক্তির সাথে মর্যাদা, সহানুভূতি এবং সম্মানের সাথে দেখা করি—কারণ নিরাময় শুরু হয় নিরাপদ বোধ করার মাধ্যমে।",
    "about.evidenceCare": "প্রমাণ-ভিত্তিক যত্ন",
    "about.evidenceDesc": "আমাদের পরিকল্পনাগুলি আধুনিক ক্লিনিকাল অনুশীলন দ্বারা পরিচালিত হয় এবং চলমান মূল্যায়ন এবং ফলাফলের মাধ্যমে সামঞ্জস্য করা হয়।",
    "about.wholePerson": "সম্পূর্ণ ব্যক্তি পদ্ধতি",
    "about.wholePersonDesc": "আমরা মন, শরীর, পরিবার এবং দৈনন্দিন জীবনকে সমর্থন করি—রোগীদের লক্ষণগুলির বাইরে স্থিতিশীলতা গড়ে তুলতে সাহায্য করা।",
    "about.emergencySupport": "জরুরি সহায়তা",
    "about.careTeams": "যত্ন দল",
    "about.patientPrivacy": "রোগী-প্রথম গোপনীয়তা",
    "about.treatmentPlans": "চিকিৎসা পরিকল্পনা",
    "about.readyToTalk": "কাউকে কথা বলতে প্রস্তুত?",
    "about.readyDesc": "আপনি যদি নিজের বা প্রিয়জনের জন্য সহায়তা খুঁজছেন, আমাদের দল আপনাকে সঠিক যত্নের পথে নির্দেশ করতে পারে।",
    "about.bookAppointment": "একটি অ্যাপয়েন্টমেন্ট বুক করুন",
    "about.callHelpline": "২৪/৭ হেল্পলাইন কল করুন",
    "about.multidisciplinary": "বহু-শৃঙ্খলাবদ্ধ",
    "about.confidential": "গোপন",
    "about.personalized": "ব্যক্তিগতকৃত",

    // Treatment Page
    "treatment.badge": "আমাদের চিকিৎসা পদ্ধতি",
    "treatment.title": "ব্যক্তিগতকৃত, প্রমাণ-ভিত্তিক",
    "treatment.titleHighlight": "মানসিক স্বাস্থ্য চিকিৎসা",
    "treatment.description": "প্রমাণিত থেরাপির সাথে সহানুভূতিশীল যত্নকে একত্রিত করে ব্যাপক, ব্যক্তিগতকৃত পরিকল্পনা যা আপনাকে স্থায়ী পুনরুদ্ধার এবং সুস্থতা অর্জনে সাহায্য করে।",
    "treatment.multidisciplinary": "২৪/৭ বহু-শৃঙ্খলাবদ্ধ দল",
    "treatment.traumaCare": "আঘাত-সচেতন, সম্মানজনক যত্ন",
    "treatment.traumaDesc": "প্রতিটি পরিকল্পনা মর্যাদা এবং নিরাপত্তাকে সম্মান করে।",
    "treatment.programs": "প্রোগ্রাম",
    "treatment.modalities": "চিকিৎসা",
    "treatment.modalitiesHighlight": "পদ্ধতি",
    "treatment.modalitiesDesc": "আপনার অনন্য প্রয়োজনের জন্য তৈরি করা চিকিৎসামূলক পদ্ধতির একটি ব্যাপক পরিসর।",
    "treatment.journey": "যাত্রা",
    "treatment.treatmentJourney": "আপনার চিকিৎসা",
    "treatment.journeyHighlight": "যাত্রা",
    "treatment.journeyDesc": "পুনরুদ্ধার এবং সুস্থতার জন্য একটি কাঠামোবদ্ধ, ধাপে ধাপে পদ্ধতি।",
    "treatment.evidence": "প্রমাণ",
    "treatment.evidenceApproaches": "প্রমাণ-ভিত্তিক",
    "treatment.evidenceHighlight": "পদ্ধতি",
    "treatment.evidenceDesc": "বৈজ্ঞানিক গবেষণা এবং প্রমাণিত চিকিৎসামূলক পদ্ধতিতে ভিত্তি করে।",
    "treatment.specializedPrograms": "বিশেষায়িত",
    "treatment.programsHighlight": "চিকিৎসা প্রোগ্রাম",
    "treatment.inpatient": "ইনপেশেন্ট চিকিৎসা",
    "treatment.inpatientDesc": "স্থির চিকিৎসা তত্ত্বাবধানের প্রয়োজন এমন ব্যক্তিদের জন্য একটি নিরাপদ, কাঠামোবদ্ধ পরিবেশে নিবিড় ২৪/৭ যত্ন।",
    "treatment.roundClock": "দিনরাত চিকিৎসা যত্ন",
    "treatment.structured": "কাঠামোবদ্ধ দৈনন্দিন প্রোগ্রাম",
    "treatment.safeEnvironment": "নিরাপদ, সহায়ক পরিবেশ",
    "treatment.outpatient": "আউটপেশেন্ট চিকিৎসা",
    "treatment.outpatientDesc": "নমনীয় চিকিৎসা বিকল্প যা আপনাকে ব্যাপক যত্ন এবং সহায়তা গ্রহণের সময় দৈনন্দিন জীবন চালিয়ে যেতে দেয়।",
    "treatment.flexible": "নমনীয় সময়সূচী",
    "treatment.maintainRoutines": "দৈনন্দিন রুটিন বজায় রাখুন",
    "treatment.familySupport": "পরিবার এবং কাজের সহায়তা",
    "treatment.beginJourney": "পুনরুদ্ধারের যাত্রা শুরু করুন",
    "treatment.beginDesc": "ভাল মানসিক স্বাস্থ্যের দিকে প্রথম পদক্ষেপ নিন। আমাদের সহানুভূতিশীল দল আপনার অনন্য প্রয়োজনের জন্য তৈরি করা একটি ব্যক্তিগতকৃত চিকিৎসা পরিকল্পনা তৈরি করতে প্রস্তুত।",
    "treatment.scheduleConsultation": "পরামর্শ নির্ধারণ করুন",
    "treatment.callNow": "এখনই কল করুন: ২৪/৭ হেল্পলাইন",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "bn")) {
      setLanguage(savedLanguage);
    }
  }, []);

  const toggleLanguage = () => {
    const newLanguage = language === "en" ? "bn" : "en";
    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
