import { Metadata } from "next";

// Article-specific metadata
const articleMetadata: Record<string, {
  title: string;
  description: string;
  keywords: string[];
  publishedTime: string;
  modifiedTime: string;
}> = {
  "understanding-mental-health": {
    title: "Understanding Mental Health: A Comprehensive Guide | Brain And Life Hospital",
    description: "Learn about mental health, common conditions, and how to seek help. Comprehensive guide to mental wellness, depression, anxiety, and professional mental health care in Bangladesh.",
    keywords: [
      // Primary keywords
      "mental health guide",
      "mental health awareness",
      "mental wellness",
      "mental health conditions",
      "mental health care Bangladesh",
      // Condition-specific
      "depression symptoms",
      "anxiety disorders",
      "bipolar disorder",
      "mental health treatment",
      "psychiatric care",
      // Location-based
      "mental health services Bangladesh",
      "mental health Dhaka",
      "psychiatric services Bangladesh",
      // Long-tail keywords
      "how to improve mental health",
      "mental health support",
      "mental health professional",
      "mental health resources",
      "signs of mental health issues",
      // Bengali keywords
      "মানসিক স্বাস্থ্য নির্দেশিকা",
      "মানসিক স্বাস্থ্য সচেতনতা",
      "মানসিক সুস্থতা",
      "মানসিক স্বাস্থ্য অবস্থা",
      "মানসিক স্বাস্থ্য যত্ন বাংলাদেশ",
      "বিষণ্নতা লক্ষণ",
      "উদ্বেগজনিত ব্যাধি",
      "মানসিক স্বাস্থ্য চিকিৎসা",
      "মনোরোগবিদ্যা যত্ন",
    ],
    publishedTime: "2026-01-15T00:00:00+00:00",
    modifiedTime: "2026-01-15T00:00:00+00:00",
  },
  "understanding-schizophrenia": {
    title: "Understanding Schizophrenia: Symptoms, Treatment, and Support | Brain And Life Hospital",
    description: "Comprehensive guide to schizophrenia: symptoms, causes, treatment options, and support. Learn about hallucinations, delusions, and effective schizophrenia management in Bangladesh.",
    keywords: [
      // Primary keywords
      "schizophrenia",
      "schizophrenia symptoms",
      "schizophrenia treatment",
      "schizophrenia causes",
      "schizophrenia diagnosis",
      // Symptom-specific
      "hallucinations",
      "delusions",
      "schizophrenia signs",
      "schizophrenia early symptoms",
      "paranoid schizophrenia",
      // Treatment-related
      "schizophrenia medication",
      "schizophrenia therapy",
      "schizophrenia support",
      "schizophrenia recovery",
      "schizophrenia management",
      // Location-based
      "schizophrenia treatment Bangladesh",
      "schizophrenia doctor Dhaka",
      "psychiatric care schizophrenia",
      // Long-tail keywords
      "what is schizophrenia",
      "how to help someone with schizophrenia",
      "schizophrenia family support",
      "schizophrenia early intervention",
      // Bengali keywords
      "স্কিজোফ্রেনিয়া",
      "স্কিজোফ্রেনিয়া লক্ষণ",
      "স্কিজোফ্রেনিয়া চিকিৎসা",
      "স্কিজোফ্রেনিয়া কারণ",
      "স্কিজোফ্রেনিয়া নির্ণয়",
      "হ্যালুসিনেশন",
      "ভ্রান্ত ধারণা",
      "স্কিজোফ্রেনিয়া চিকিৎসা বাংলাদেশ",
      "স্কিজোফ্রেনিয়া ডাক্তার ঢাকা",
    ],
    publishedTime: "2026-01-28T00:00:00+00:00",
    modifiedTime: "2026-01-28T00:00:00+00:00",
  },
  "drug-addiction": {
    title: "Understanding Drug Addiction: Causes, Effects, and Recovery | Brain And Life Hospital",
    description: "Comprehensive guide to drug addiction: causes, warning signs, effects, and treatment options. Learn about substance abuse recovery, detoxification, and addiction rehabilitation in Bangladesh.",
    keywords: [
      // Primary keywords
      "drug addiction",
      "substance abuse",
      "drug addiction treatment",
      "addiction recovery",
      "drug rehabilitation",
      // Substance-specific
      "heroin addiction",
      "yaba addiction",
      "marijuana addiction",
      "phensedyl addiction",
      "opioid addiction",
      "cocaine addiction",
      // Treatment-related
      "addiction treatment center",
      "drug detox",
      "addiction therapy",
      "substance abuse treatment",
      "addiction counseling",
      // Location-based
      "drug addiction treatment Bangladesh",
      "addiction rehabilitation Dhaka",
      "drug rehab Bangladesh",
      "substance abuse treatment Bangladesh",
      // Long-tail keywords
      "signs of drug addiction",
      "drug addiction symptoms",
      "how to overcome drug addiction",
      "drug addiction help",
      "addiction recovery program",
      "drug addiction support",
      // Bengali keywords
      "মাদকাসক্তি",
      "মাদক অপব্যবহার",
      "মাদকাসক্তি চিকিৎসা",
      "মাদকাসক্তি পুনরুদ্ধার",
      "মাদক পুনর্বাসন",
      "হেরোইন আসক্তি",
      "ইয়াবা আসক্তি",
      "মারিজুয়ানা আসক্তি",
      "ফেনসিডিল আসক্তি",
      "মাদকাসক্তি চিকিৎসা কেন্দ্র",
      "মাদক ডিটক্স",
      "মাদকাসক্তি থেরাপি",
      "মাদকাসক্তি চিকিৎসা বাংলাদেশ",
      "মাদকাসক্তি পুনর্বাসন ঢাকা",
      "মাদকাসক্তির লক্ষণ",
      "মাদকাসক্তি থেকে মুক্তি",
    ],
    publishedTime: "2026-02-05T00:00:00+00:00",
    modifiedTime: "2026-02-05T00:00:00+00:00",
  },
  "early-signs-of-depression": {
    title: "Early Signs of Depression Most People Ignore | Brain And Life Hospital",
    description: "Learn about the early warning signs of depression that many people overlook. Discover subtle symptoms like fatigue, sleep changes, loss of interest, concentration difficulties, and when to seek professional help for depression treatment in Bangladesh.",
    keywords: [
      // Primary keywords
      "depression signs",
      "early depression symptoms",
      "depression warning signs",
      "depression symptoms",
      "depression early signs",
      "depression ignored signs",
      "depression overlooked symptoms",
      // Symptom-specific
      "depression fatigue",
      "depression sleep problems",
      "depression insomnia",
      "depression oversleeping",
      "loss of interest depression",
      "depression concentration",
      "depression difficulty concentrating",
      "depression appetite changes",
      "depression weight changes",
      "depression irritability",
      "depression mood swings",
      "depression physical symptoms",
      "depression headaches",
      // Condition-specific
      "major depressive disorder",
      "clinical depression",
      "depression disorder",
      "depressive symptoms",
      // Treatment-related
      "depression treatment",
      "depression help",
      "depression therapy",
      "depression medication",
      "depression support",
      "depression counseling",
      "depression intervention",
      "depression recovery",
      // Location-based
      "depression treatment Bangladesh",
      "depression doctor Dhaka",
      "depression psychiatrist Bangladesh",
      "mental health depression",
      "depression care Bangladesh",
      "depression clinic Dhaka",
      // Long-tail keywords
      "signs of depression",
      "early signs of depression",
      "depression symptoms to watch for",
      "when to seek help for depression",
      "depression warning signs",
      "depression red flags",
      "hidden signs of depression",
      "subtle depression symptoms",
      "depression symptoms ignored",
      "how to recognize depression",
      "depression early detection",
      // Bengali keywords
      "বিষণ্নতার লক্ষণ",
      "বিষণ্নতার প্রাথমিক লক্ষণ",
      "বিষণ্নতার সতর্কতা লক্ষণ",
      "বিষণ্নতার উপসর্গ",
      "বিষণ্নতা ক্লান্তি",
      "বিষণ্নতা ঘুমের সমস্যা",
      "বিষণ্নতা অনিদ্রা",
      "আগ্রহ হারানো বিষণ্নতা",
      "বিষণ্নতা মনোযোগ",
      "বিষণ্নতা ক্ষুধা",
      "বিষণ্নতা চিকিৎসা",
      "বিষণ্নতা সাহায্য",
      "বিষণ্নতা থেরাপি",
      "বিষণ্নতা চিকিৎসা বাংলাদেশ",
      "বিষণ্নতা ডাক্তার ঢাকা",
      "বিষণ্নতার লক্ষণ দেখার জন্য",
      "বিষণ্নতার জন্য কখন সাহায্য চাইতে হয়",
      "বিষণ্নতার লুকানো লক্ষণ",
      "বিষণ্নতা চিনতে কীভাবে",
    ],
    publishedTime: "2026-02-10T00:00:00+00:00",
    modifiedTime: "2026-02-10T00:00:00+00:00",
  },
  "exam-stress-student-anxiety": {
    title: "Exam Stress and Student Anxiety: Practical Coping Tips | Brain And Life Hospital",
    description: "Learn practical strategies to manage exam stress and student anxiety. Discover evidence-based coping techniques including time management, relaxation methods, cognitive strategies, study tips, and when to seek professional help for test anxiety and academic stress in Bangladesh.",
    keywords: [
      // Primary keywords
      "exam stress",
      "student anxiety",
      "test anxiety",
      "exam anxiety",
      "study stress",
      "academic stress",
      "exam preparation",
      "stress management",
      "anxiety management",
      "student mental health",
      // Student-specific
      "academic performance",
      "exam performance",
      "study tips",
      "exam tips",
      "test preparation",
      "exam strategies",
      "study techniques",
      "exam success",
      "academic success",
      // Coping strategies
      "exam coping strategies",
      "test anxiety tips",
      "stress relief",
      "anxiety relief",
      "relaxation techniques",
      "deep breathing exercises",
      "progressive muscle relaxation",
      "mindfulness for students",
      "meditation for exam stress",
      "time management",
      "study schedule",
      "study planning",
      // Physical health
      "sleep and exams",
      "exercise and stress",
      "nutrition for students",
      "exam day preparation",
      // Cognitive strategies
      "cognitive behavioral therapy",
      "positive thinking",
      "negative thought patterns",
      "exam confidence",
      "self-talk",
      // Treatment-related
      "student counseling",
      "anxiety treatment",
      "stress counseling",
      "academic counseling",
      "student therapy",
      "mental health support students",
      "anxiety therapy",
      "stress therapy",
      // Location-based
      "exam stress Bangladesh",
      "student anxiety Bangladesh",
      "test anxiety Bangladesh",
      "student counseling Bangladesh",
      "academic stress Bangladesh",
      "student mental health Bangladesh",
      "exam stress Dhaka",
      "student counseling Dhaka",
      // Long-tail keywords
      "how to manage exam stress",
      "coping with test anxiety",
      "exam stress management",
      "student anxiety help",
      "test anxiety treatment",
      "academic stress relief",
      "exam preparation tips",
      "study stress management",
      "how to reduce exam anxiety",
      "overcoming test anxiety",
      "managing exam pressure",
      "dealing with exam stress",
      "exam anxiety symptoms",
      "signs of exam stress",
      "when to seek help for exam stress",
      "exam stress support",
      "student stress management",
      "academic anxiety help",
      // Bengali keywords
      "পরীক্ষার চাপ",
      "ছাত্র উদ্বেগ",
      "পরীক্ষার উদ্বেগ",
      "অধ্যয়ন চাপ",
      "একাডেমিক চাপ",
      "চাপ ব্যবস্থাপনা",
      "উদ্বেগ ব্যবস্থাপনা",
      "ছাত্র মানসিক স্বাস্থ্য",
      "পরীক্ষার পারফরম্যান্স",
      "একাডেমিক পারফরম্যান্স",
      "অধ্যয়ন টিপস",
      "পরীক্ষার টিপস",
      "চাপ উপশম",
      "উদ্বেগ উপশম",
      "শিথিলকরণ কৌশল",
      "সময় ব্যবস্থাপনা",
      "অধ্যয়ন সময়সূচী",
      "পরীক্ষার চাপ বাংলাদেশ",
      "ছাত্র উদ্বেগ বাংলাদেশ",
      "ছাত্র কাউন্সেলিং বাংলাদেশ",
      "পরীক্ষার চাপ কীভাবে পরিচালনা করবেন",
      "পরীক্ষার উদ্বেগ মোকাবিলা",
      "পরীক্ষার চাপ কমানোর উপায়",
      "পরীক্ষার উদ্বেগ কাটিয়ে ওঠা",
      "পরীক্ষার চাপের লক্ষণ",
      "ছাত্র মানসিক স্বাস্থ্য বাংলাদেশ",
    ],
    publishedTime: "2026-02-15T00:00:00+00:00",
    modifiedTime: "2026-02-15T00:00:00+00:00",
  },
};

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const slug = params.slug;
  const metadata = articleMetadata[slug] || articleMetadata["understanding-mental-health"];
  const baseUrl = "https://brainandlifehospital.com";
  const articleUrl = `${baseUrl}/articles/${slug}`;

  return {
    title: metadata.title,
    description: metadata.description,
    keywords: metadata.keywords,
    authors: [{ name: "Brain And Life Hospital" }],
    creator: "Brain And Life Hospital",
    publisher: "Brain And Life Hospital",
    openGraph: {
      title: metadata.title,
      description: metadata.description,
      url: articleUrl,
      siteName: "Brain And Life Hospital",
      images: [
        {
          url: `${baseUrl}/og-image.jpg`,
          width: 1200,
          height: 630,
          alt: metadata.title,
        },
      ],
      locale: "en_US",
      type: "article",
      publishedTime: metadata.publishedTime,
      modifiedTime: metadata.modifiedTime,
    },
    twitter: {
      card: "summary_large_image",
      title: metadata.title,
      description: metadata.description,
      images: [`${baseUrl}/og-image.jpg`],
    },
    alternates: {
      canonical: articleUrl,
      languages: {
        en: articleUrl,
        bn: `${articleUrl}?lang=bn`,
        "x-default": articleUrl,
      },
    },
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: false,
        nosnippet: false,
      },
    },
  };
}

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
